spring:
      application:
        name: blog
      datasource:
        url: jdbc:postgresql://localhost:5432/blog
        username: postgres
        password: postgres
      jpa:
        hibernate:
          ddl-auto: update
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
#  secret: ${jwt.secret}
   secret: b78d391807cf6fa92141debff106cf931e13085c20729275167a751536a54e12